name: React Vite CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Khai báo chuẩn: ÉP tất cả các lệnh run phía dưới phải chạy bên trong thư mục first-react-app
    defaults:
      run:
        working-directory: ./first-react-app

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Cài đặt Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cài đặt thư viện dependencies
      working-directory: ./first-react-app
      run: npm install

    - name: Kiểm tra lỗi Code (Lint)
      working-directory: ./first-react-app
      run: npm run lint --if-present

    - name: Biên dịch dự án (Build thử)
      working-directory: ./first-react-app
      run: npm run build --if-present